name: dukahub
description: "A mobile app platform for grassroots shopkeepers and customers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFC20E"
  image: "assets/icons/splash_logo.png"

  android_gravity: center
  ios_content_mode: scaleAspectFit

  android_12:
    color: "#FFC20E"
    image: "assets/icons/splash_logo.png"
    icon_background_color: "#FFC20E"

  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf
        - asset: assets/fonts/Urbanist-Italic-VariableFont_wght.ttf
          style: italic